# Generated by Django 4.1.7 on 2023-06-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user_role",
            options={"verbose_name": "user_role", "verbose_name_plural": "users_roles"},
        ),
        migrations.RenameField(
            model_name="user_role",
            old_name="role",
            new_name="user_role",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default="saler",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="role",
                to="users.user_role",
            ),
        ),
    ]
