# Generated by Django 4.1.7 on 2023-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_role",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("saler", "saler"),
                    ("manager", "manager"),
                    ("technician", "technician"),
                ],
                max_length=10,
            ),
        ),
    ]
