# Generated by Django 4.1.7 on 2023-06-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default="saler",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="role",
                to="users.user_role",
            ),
        ),
        migrations.AlterField(
            model_name="user_role",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("saler", "saler"),
                    ("manager", "manager"),
                    ("technician", "technician"),
                ],
                default="saler",
                max_length=10,
            ),
        ),
    ]
