# Generated by Django 4.1.7 on 2023-06-15 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("upcoming", "upcoming"),
                            ("current", "current"),
                            ("finished", "finished"),
                        ],
                        default="upcoming",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event_status",
                "verbose_name_plural": "Events_status",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("attendees", models.IntegerField()),
                ("event_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(max_length=500)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_id",
                        to="clients.client",
                    ),
                ),
                (
                    "event_status",
                    models.ForeignKey(
                        default="upcoming",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="event_status",
                        to="events.event_status",
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
    ]
