# Generated by Django 4.2.2 on 2023-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_sales_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="existing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
